### ISSUE TITLE
Error when building the project

### ISSUE THREAD

**Issue by easybeau** [leanpanda-com/fermo#1]
Hi,

When I ran `mix fermo.build`, I got this message 

![error-morphix](https://user-images.githubusercontent.com/7128391/87780577-4aab9b80-c82f-11ea-9c69-2219efb2f281.png)

I tried to update, recompile and clean morphix.

Could you help me.
Thanks

**Comment by joeyates** [comment]
Hi @easybeau 

Sorry for not getting back to you. This problem was fixed, but you didn't get notified.
